/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ft42.communic;

import org.junit.Test;

public class LibraryTest {
	@Test
	public void testSomeLibraryMethod() {

	}
}
